version: "3.5"
networks:
  api_net:
    name: api_net
services:
  database:
    image: "postgres" # use latest official postgres version
    ports: 
      - "5432:5432"
    networks:
      - api_net
    environment:
      - POSTGRES_DB=sample
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    # Main application
  api:
    build:
      context: .
    command: ["pizza-app","api"]
    networks:
      - api_net
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=${POSTGRES_DB_HOST}
      - POSTGRES_PORT=${POSTGRES_DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
